### ISSUE TITLE
Specify a “callback url” in the header

### ISSUE THREAD

**Issue by tpmccallum** [second-state/wasm-joey#12]
When the function returns, it will post the result to the callback url.

**Comment by tpmccallum** [comment]
This will be useful when executing a single function as per this endpoint `/api/run/:wasm_id/:function_name`

**Comment by juntao** [comment]
We should also support callback_url_headers. It is a JSON array of http headers. That is needed because the callback could require header-based authentication. Example:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Authentication

**Comment by juntao** [comment]
Per our discussion on slack, we should NOT add this header. Instead, Joey should support a `callback` JSON element in the function return value (only applies when the function returns a string). 

If this `callback` element is present, Joey will remove it from the result, and then send the result to the `callback` as the http request body. The `callback` element structure is as follows.

```
'callback': {
  'url': 'http://next.com/next',
  'method': 'POST',
  'headers': [
    'name1': 'value1',
    'name2': 'value2'
  ]
}
```

**Comment by tpmccallum** [comment]
Callback is now implemented.
Documentation is located at the following URL
https://web.postman.co/collections/4967217-84b93d68-2073-4f51-bde3-68f19de57c62?version=latest&workspace=6683d8e5-f543-4751-8871-aeceebf90811#2b37d947-1b86-4d51-b836-40359e8b92a4
