### ISSUE TITLE
Specify an "argument_url" in the header

### ISSUE THREAD

**Issue by juntao** [second-state/wasm-joey#16]
I think the function caller should be able to give an `argument_url` in the function exec request. Joey will fetch the URL content and pass it into the function as call argument (as a string or byte array depending on the `argument_url` content type).

This way, we can make it easier to chain Joey functions. For example, we could create an image / video processing function that simply takes a URL and returns the results back into a remote hosting service.

This issue is related to #12

**Comment by juntao** [comment]
A concrete use case is to use a web-based cron service like https://cron-job.org/en/faq/

For example, it could send the NASA Picture of the Day every 24 hours to Joey for processing, and Joey can send the result to S3 or via email.

The cron service can send in the picture URL in requests to trigger Joey functions, but cannot download and cache the picture before calling Joey.

**Comment by juntao** [comment]
If the caller pass in both `argument_url` and an HTTP body, we will join the two bodies and pass all arguments to the function. That allows the caller to pass in additional meta data information, such as the storage ID for stateful function calls.

**Comment by juntao** [comment]
Per our discussion on slack, we should NOT add this header. Instead, Joey should first determine if the request is `multipart/*`. If it is, Joey looks for a `text/json` part with name `argument`.

If this `argument` JSON element is present, Joey will get content from it, and then pass its content as a call argument (after state). The content can be bytes or string. 

The `argument` JSON string in the request is as follows.

```
{
  'url': 'http://next.com/next',
  'method': 'POST',
  'headers': [
    'name1': 'value1',
    'name2': 'value2'
  ]
}
```

**Comment by tpmccallum** [comment]
This is now complete.
