### ISSUE TITLE
Provide logging via `logging_callback_url`

### ISSUE THREAD

**Issue by tpmccallum** [second-state/wasm-joey#17]
Create a mechanism to write details of activities in a way that it is queryable 

If a caller sends a request and does not want the response in a body, but rather provides a callback_url to direct the response to another service/task

In these cases the caller is not waiting on a promise etc. they just assume that the rest of the RESTful requests were performed and worked as expected

We could provide a logging callback_url which would essentially spawn off a request which will write to database and log action i.e. who was just called? what were the parameters?

This way if a part of the system is failing the logs will show where the callback_url chain halted i.e. what the last successful thing to execute was.

This can all be done in parallel with the actual functional work that is being performed via callback_urls

**Comment by juntao** [comment]
Is it possible to just store on Joey and provide an API to query the log? This way the log will always be available even if the logging url is unavailable for some reason.

**Comment by tpmccallum** [comment]
Yes, Joey could store a timestamp and some context i.e. the `wasm_state` for that particular `wasm_id` upon Wasm execution. There will still be a record of what the callback URLs were at a specific execution, even if the user updates the `wasm_state` post execution.

**Comment by tpmccallum** [comment]
We now [log each callback's execution](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L137) as well as [log each initial wasm execution](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L364).

The logs are stored in a separate table in Joey. The `wasm_execution_log` table is keyed back to the original `wasm_executables` table so that we can build SQL queries in the future.

At present a caller can obtain the data in the `wasm_execution_log` table in the same way that they can obtain data in the original `wasm_executables` table. Specifically, through the use of filters.

Here is an example of providing an API query to the log:

```
https://rpc.ssvm.secondstate.io:8081/api/log/1?filterBy=[ "execution_timestamp", "execution_object"]
```

Valid filters include
`log_id` - fresh ID when log is created
`wasm_executable_id` - the id of the wasm executable that was called at the outset
`wasm_executable_state` - the state context of the wasm executable as at the time the `run` or `callback` was executed
`execution_timestamp` - the time when the `run` or `callback` was executed
`execution_object` - a JSON object containing all of the relevant execution information i.e. payload (request body), callback options object (created in the Rust) if applicable, callback payload (a record of the output of the first Rust Wasm execution which is being passed to the callback)
