### ISSUE TITLE
Support stateful context

### ISSUE THREAD

**Issue by juntao** [second-state/wasm-joey#19]
There is a context for each wasm file. The context is a string and can be set with a separate API call. Every wasm function call’s first argument is always this context string — even if it is empty. The function developer must take this into account when he processes the input arguments.

**Comment by tpmccallum** [comment]
This new field has now been added.
When a new Wasm executable is set into the system, a blank `wasm_state` field is created (a JSON string column in Joey's database).

From there [an endpoint](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L347) exists, to which a user can add any valid JSON string (to be stored in the `wasm_state` column, for that `wasm_id` in the database).

The execution from Joey to SSVM will look like this
```
 ... SELECT wasm_binary, wasm_state FROM wasm_executables ... as callback called "result"
var wasm_state_as_string = result[0].wasm_state;
var wasm_as_buffer = Uint8Array.from(result[0].wasm_binary);
var vm = new ssvm.VM(wasm_as_buffer);
var return_value = vm.RunString(wasm_state_as_string, function_name, function_parameters_as_string); 
json_response["return_value"] = return_value;
```

**Comment by tpmccallum** [comment]
If a user does not want to apply any context via the `wasm_state` feature they can just completely ignore it and their code will still work i.e. if someone writes a simple hello_world that does not require the context feature.
