### ISSUE TITLE
Support text/plain in /api/state

### ISSUE THREAD

**Issue by juntao** [second-state/wasm-joey#20]
The context state string could be a simple text/plain string. Joey will just save the string and pass it to the function at /api/run.

**Comment by tpmccallum** [comment]
Yes, the context state is a plain string that is [set to a blank](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L165) string when a wasm executable is set into the system.

From there a user can [change this context state string](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L439) via a PUT request to the `/api/state/:wasm_id` endpoint.

The `/api/run/:wasm_id/:function_name` endpoint [passes the context state string](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L327) into the function as it is called.
